apiVersion: apps/v1
kind: Deployment
metadata:
  name: elaview-api-gateway
  labels:
    app: elaview-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elaview-api-gateway
  template:
    metadata:
      labels:
        app: elaview-api-gateway
    spec:
      containers:
        - name: elaview-api-gateway
          image: nginx
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: elaview-api-gateway